#!/bin/bash
PATH=`pwd`
if [ $UID != 0 ];
  then
    echo 'Please go root!';
    exit 1
fi

if [ "$1" == "" ];
  then
    echo 'Usage: htaccess USERNAME';
    exit 1
fi

/bin/touch .htaccess
/bin/touch .htpasswd

echo "AuthUserFile $PATH/.htpasswd" > .htaccess
echo 'AuthName "Login"' >> .htaccess
echo 'AuthType Basic' >> .htaccess
echo '<Limit GET>' >> .htaccess
echo 'require valid-user' >> .htaccess
echo '</Limit>' >> .htaccess
echo 'Options -Indexes' >> .htaccess

/usr/sbin/htpasswd $PATH/.htpasswd $1
